apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: evtol-index-default
  namespace: shmape
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values: [evtol-index-web, evtol-index-worker]
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 443
